import "./globals.css";
import { Inter } from "next/font/google";
import type { Metadata } from "next";
// components
import Header from "@/components/Header";
import Footer from "@/components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-body bg-cover bg-no-repeat`}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
